name: recflix-env
dependencies:
  - python=3.9
  - pip
  - pip:
      - protobuf==3.20.0
      - grpcio-tools
      - pymilvus==2.5.6
      - "pymilvus[model]"
      - python-dotenv
      - sentence-transformers
      - tf-keras
      - streamlit
      - redis